### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Bjornsson** [BamUnique/Dungeon-Crawler-Game#1]
Hey Banjo,

are there some docs on how to install and use the game? I have never installed a game like this on my Mac. How do I best do that? Cheers Bjorn

**Comment by BamUnique** [comment]
Hey Bjorn. Currently this version is still in progress so there isn’t much to it. You can only really choose your character at the moment. However to install there should be a download zip file. And once you download it then you need to make sure you have a way to run the code. This is normally done through an IDE like Idle or PyCharm. Then you need to make sure that the file is in the folder where your projects for the IDE are located and you should be able to then open the file in the IDE. Then you should see a number of .py and .json files (I see them on the left when using PyCharm), then you would right click on the file called main.py and click run. Then the game should work.

**Comment by BamUnique** [comment]
It should be a green button called Code with a dropdown menu then download the zip
